### ISSUE TITLE
镜像创建或源码创建组件时，更改构建源不应该出现两个选项

### ISSUE THREAD

**Issue by zhangdonglin-90528** [wutong-paas/wutong-ui#137]
镜像创建或源码创建组件时，更改构建源不应该出现两个选项，应只出现对应设置
![image](https://user-images.githubusercontent.com/97881485/189086110-b43d15c3-76a5-42f9-a1f4-91abb6b723df.png)

**Comment by zhangdonglin-90528** [comment]
![image](https://user-images.githubusercontent.com/97881485/189087408-bd94566f-6277-4e9c-bb3f-c39894375143.png)

**Comment by maoxiaodun** [comment]
fixed
