### ISSUE TITLE
新建组件按钮未进行防抖

### ISSUE THREAD

**Issue by zhangdonglin-90528** [wutong-paas/wutong-ui#145]
新建组件按钮未进行防抖，可重复点击

<img width="302" alt="bea8647b6761a38ea34dd1aec1c0b18" src="https://user-images.githubusercontent.com/97881485/192422655-fed0f022-4ce5-4f83-b95f-be88c8dadb73.png">

**Comment by maoxiaodun** [comment]
已修复，随大版本更新上线
